name: Download & Upload

on:
  workflow_dispatch:
    inputs:
      URLA:
        required: true
      URLB:
        required: true
      URLC:
        required: true
      RELEASE_NAME:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Download & MD5
      run: |
        mkdir temp
        cd temp
        wget ${{ github.event.inputs.URLA }}
        wget ${{ github.event.inputs.URLB }}
        wget ${{ github.event.inputs.URLC }}
        md5sum *

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          temp/*.img
          temp/*.zip
          temp/*.7z
          temp/*.xz
        name: ${{ github.event.inputs.RELEASE_NAME }}
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
